name: build-app

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'


jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.2.1
      with:
        host: ${{ vars.SONARQUBE_URL }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
  build-linux:
    name: build-app-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '21.x'

      - name: Install yarn
        run:  npm -g install yarn

      - name: Install packages
        run: yarn install

      - name: Build package
        id: build
        run: |
          echo "APP_NAME=$(node copyExec.js | awk '/VERSION: / {print $2}')" >> $GITHUB_ENV
      
      - name: Log version
        run: |
          echo "${{ env.APP_NAME }}"

      - name: Release
        if: github.ref_type == 'tag'
        uses: akkuman/gitea-release-action@v1
        with:
          files: |
            ${{ env.APP_NAME }}

  build-windows:
    name: build-app-windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '21.x'

      - name: Install yarn
        run:  npm -g install yarn

      - name: Install packages
        run: yarn install

      - name: Build package
        id: build
        run: |
          echo "APP_NAME=$(node copyExec.js | awk '/VERSION: / {print $2}')" >> $GITHUB_ENV
      
      - name: Log version
        run: |
          echo "${{ env.APP_NAME }}"

      - name: Release
        if: github.ref_type == 'tag'
        uses: akkuman/gitea-release-action@v1
        with:
          files: |
            ${{ env.APP_NAME }}
      
      