name: build-app

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'


jobs:
  build-linux:
    name: build-app-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '21.x'

      - name: Install yarn
        run:  npm -g install yarn

      - name: Install packages
        run: yarn install

      - name: Build package
        id: build
        run: |
          echo "APP_NAME=$(node copyExec.js)" >> $GITHUB_OUTPUT

      - name: Release
        if: github.ref_type == 'tag'
        uses: akkuman/gitea-release-action@v1
        with:
          files: |
            ${{ steps.build.outputs.APP_NAME }}
      